# Generated by Django 4.2.1 on 2023-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_currentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='currentPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
