# Generated by Django 4.2.1 on 2023-06-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_currentprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='listingActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='winner',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
